name: Test local environment in a Pull request environment

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test changes
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY }}
          test-suite-id: cluikotlj000113mzj16udtno
          github-comment: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
